(function (root) {
  const fields = [
    {
      key: 'poliza',
      label: 'PÓLIZA',
      cell: 'A',
      voice: 'chars',
      placeholder: 'EJ. AZG632',
      help: 'Letras y números · siempre mayúsculas',
    },
    {
      key: 'nombre',
      label: 'NOMBRE COMPLETO',
      cell: 'B',
      voice: 'words',
      placeholder: 'APELLIDO PATERNO, MATERNO Y NOMBRES',
      required: true,
      span: 2,
      help: 'La lupa busca por cualquier parte del nombre o apellido',
    },
    {
      key: 'negocio',
      label: 'NEGOCIO',
      cell: 'C',
      options: ['', 'NUEVA', 'INCREMENTO', 'INCLUSION'],
      required: true,
    },
    {
      key: 'suma',
      label: 'SUMA ASEGURADA',
      cell: 'D',
      type: 'money',
      voice: 'number',
      placeholder: '100,000',
      required: true,
    },
    {
      key: 'prima',
      label: 'PRIMA',
      cell: 'E',
      type: 'decimal',
      voice: 'number',
      placeholder: '239.92',
      required: true,
    },
    {
      key: 'primaExcedente',
      label: 'PRIMA EXCEDENTE',
      cell: 'F',
      type: 'decimal',
      voice: 'number',
      placeholder: '0.00',
    },
    { key: 'medio', label: 'MEDIO', cell: 'G', options: ['', 'FISICA', 'PRO'], required: true },
    {
      key: 'vendida',
      label: 'VENDIDA',
      cell: 'H',
      voice: 'words',
      placeholder: 'EJ. TOÑO',
      required: true,
    },
    {
      key: 'estatus',
      label: 'ESTATUS',
      cell: 'I',
      placeholder: 'SE GUARDA EN BLANCO',
      disabled: true,
    },
    {
      key: 'telefono',
      label: 'TELÉFONO',
      cell: 'J',
      voice: 'digits',
      type: 'tel',
      placeholder: '10 DÍGITOS',
      required: true,
    },
    {
      key: 'fecha',
      label: 'FECHA',
      cell: 'K',
      voice: 'date',
      type: 'dateText',
      placeholder: 'DD/MM/AAAA',
      required: true,
      help: 'Escribe solo los números',
    },
    {
      key: 'rfc',
      label: 'RFC',
      cell: 'L',
      voice: 'chars',
      placeholder: 'SABE800311LN2',
      help: 'Opcional. Puedes guardar datos incompletos.',
    },
    {
      key: 'curp',
      label: 'CURP',
      cell: 'M',
      voice: 'chars',
      placeholder: 'SABE800311HVZNTM01',
      help: 'Opcional. Puedes guardar datos incompletos.',
    },
    {
      key: 'correo',
      label: 'CORREO ELECTRÓNICO',
      cell: 'N',
      voice: 'email',
      type: 'email',
      placeholder: 'nombre@correo.com',
      span: 2,
      help: 'El correo siempre se guarda en minúsculas',
    },
    {
      key: 'trabajo',
      label: 'LUGAR DE TRABAJO',
      cell: 'O',
      voice: 'words',
      placeholder: 'EMPRESA O INSTITUCIÓN',
    },
    {
      key: 'comunidad',
      label: 'COMUNIDAD O MUNICIPIO',
      cell: 'P',
      voice: 'words',
      placeholder: 'MUNICIPIO',
      span: 2,
    },
    {
      key: 'talon',
      label: 'TALÓN O CUENTA BANCARIA',
      cell: 'Q',
      options: ['', 'CTA. BANCARIA', 'TALON', 'C. HIBRIDA'],
      required: true,
    },
  ];
  const labels = {
    POLIZA: 'poliza',
    PÓLIZA: 'poliza',
    NOMBRE: 'nombre',
    'NOMBRE COMPLETO': 'nombre',
    NEGOCIO: 'negocio',
    'SUMA ASEGURADA': 'suma',
    PRIMA: 'prima',
    'PRIMA EXCEDENTE': 'primaExcedente',
    MEDIO: 'medio',
    VENDIDA: 'vendida',
    ESTATUS: 'estatus',
    TELEFONO: 'telefono',
    TELÉFONO: 'telefono',
    FECHA: 'fecha',
    RFC: 'rfc',
    CURP: 'curp',
    'CORREO ELECTRONICO': 'correo',
    'CORREO ELECTRÓNICO': 'correo',
    'LUGAR DE TRABAJO': 'trabajo',
    'NOMBRE DE LA COMUNIDAD O MUNICIPIO': 'comunidad',
    'COMUNIDAD O MUNICIPIO': 'comunidad',
    'TALON O CUENTA BANCARIA': 'talon',
    'TALÓN O CUENTA BANCARIA': 'talon',
  };

  const api = { fields, labels, keys: fields.map((f) => f.key) };
  if (typeof module !== 'undefined') module.exports = api;
  else root.MetlifeFields = api;
})(typeof window !== 'undefined' ? window : globalThis);
