/* Client identity survives archive deletion; file membership is explicit. */
function clientFile(item){return historyFiles().find(f=>f.batch===item?._batch);}
function clientFileLabel(item){const file=clientFile(item);return file?'Archivo: '+file.name:item?._batch===batch?'Excel actual (sin archivar)':'Solo en la nube · sin Excel guardado';}
function renderSelectedClient(){const item=window.metlifeSelectedClient;get('selectedClientActions').hidden=!item;if(!item)return;get('selectedClientLocation').textContent=(item.nombre||item.poliza||'Cliente')+' · '+clientFileLabel(item);get('attachSelectedClient').hidden=!!clientFile(item);}
function longClientNotice(message,actions=[]){const box=get('recordLocationNotice');box.replaceChildren(textNode('p',message));const controls=document.createElement('div');controls.className='workflow-actions';for(const [label,action] of actions){const button=textNode('button',label);button.type='button';button.className='secondary';button.onclick=async()=>{button.disabled=true;try{await action();}catch(error){showToast('No se completó la acción',error.message,true);}finally{button.disabled=false;}};controls.append(button);}const dismiss=textNode('button','Cerrar aviso');dismiss.type='button';dismiss.className='link-btn';dismiss.onclick=()=>box.hidden=true;controls.append(dismiss);box.append(controls);box.hidden=false;}
async function viewRecordFile(item){const file=clientFile(item);if(!file&&item._batch!==batch)throw Error('El registro está solo en la nube. Puedes agregarlo a un Excel.');await changeBatch(item._batch);get('recordScope').value='current';get('searchInput').value=item.poliza||item.nombre||'';renderRecords();document.querySelector('.records-card').scrollIntoView({behavior:'smooth'});}
function showCloudRecent(){get('recordScope').value='cloud';get('searchInput').value='';get('copiedFilter').value='all';for(const input of document.querySelectorAll('.record-filters input,.record-filters select'))input.value=input.id==='filterReview'?'all':'';selectedRecords.clear();renderRecords();}
async function notifyClientUpdate(item){
  const file=clientFile(item);showCloudRecent();
  if(file){await refreshArchive(item._batch);const failed=archiveErrors.get(item._batch);longClientNotice(failed?'Se actualizaron los datos del cliente en la nube y en los registros del archivo «'+file.name+'». La copia Excel todavía está pendiente de actualizar: '+failed+'. Puedes abrir ese archivo para revisar o copiar los datos; vuelve a intentar actualizar el Excel antes de descargarlo.':'Se actualizaron los datos en el archivo «'+file.name+'». El registro conserva su lugar en ese archivo del historial y su copia Excel está actualizada. Puedes abrirlo para copiar el registro, revisar todos sus datos o descargar la versión actualizada. También aparece en Registros recientes, en la vista de actividad de la nube.',[['Ver archivo '+file.name,()=>viewRecordFile(item)]]);
  }else if(item._batch===batch){longClientNotice('Se actualizaron los datos en el Excel actual «'+currentExcelLabel(batch)+'» y en la nube. El archivo todavía no está guardado en el historial; puedes guardarlo cuando quieras. El registro también aparece en Registros recientes.');}
  else{longClientNotice('Se actualizó el registro dentro de la nube. No pertenece a ningún Excel guardado, por lo que no se modificó un archivo del historial. Todos sus datos siguen disponibles al buscar por póliza o nombre. Cuando quieras, podrás agregar este mismo registro a un Excel nuevo, al Excel actual o a uno anterior que ya tenga otros registros, sin volver a capturar sus datos.',[['Agregar a un Excel',()=>openAttachClient(item)]]);}
}
get('editSelectedClient').onclick=async()=>{const item=window.metlifeSelectedClient;if(!item)return;const button=get('editSelectedClient');button.disabled=true;try{const fresh=await cloud.fetchRecord(item._id);if(!fresh||fresh._deletedAt)throw Error('Este cliente ya no está disponible.');if(cloud.recordRevision(fresh)!==cloud.recordRevision(item))throw Error('Los datos cambiaron en otro dispositivo. Vuelve a buscar al cliente antes de editar.');editingRecord={...fresh};reviewSignature=null;summarySignature=null;queueDraftSave();updateCaptureContext();get('nombre').focus();longClientNotice(clientFile(fresh)?'Estás editando el registro del archivo «'+clientFile(fresh).name+'». Al guardar se actualizará ese archivo y te indicaremos dónde revisarlo.':'Estás editando un cliente conservado en la nube. Al guardar se mantendrán sus datos, aunque no tenga un Excel en el historial. Después podrás elegir a qué archivo agregarlo.');}catch(error){showToast('No se pudo editar',error.message,true);}finally{button.disabled=false;}};
get('deleteSelectedClient').onclick=async()=>{const item=window.metlifeSelectedClient;if(!item||!confirm('¿Eliminar este cliente de la nube y de su Excel? Dejará de aparecer en la búsqueda y podrás recuperarlo desde la papelera durante 3 meses.'))return;const button=get('deleteSelectedClient');button.disabled=true;try{await cloud.trashRecord(item);clearForm();forgetUndo();showCloudRecent();longClientNotice('El cliente fue enviado a la papelera. Ya no aparece en las búsquedas normales. Puedes recuperarlo durante 3 meses desde la fecha de eliminación.');}catch(error){showToast('No se eliminó el cliente',error.message,true);}finally{button.disabled=false;}};
get('attachSelectedClient').onclick=()=>openAttachClient(window.metlifeSelectedClient).catch(error=>showToast('No se pudo abrir el archivo de destino',error.message,true));
const attachDialog=makeDialog('attachClientDialog','Agregar cliente a un Excel');
async function openAttachClient(item){
  if(!item)return;const current=await cloud.fetchRecord(item._id);if(!current||current._deletedAt)throw Error('El cliente ya no está disponible.');
  attachDialog.replaceChildren(textNode('h2','Agregar cliente a un Excel'),textNode('p',(current.nombre||current.poliza||'Cliente')+'. Se agregan los datos guardados en la nube; guarda primero cualquier edición del formulario.'));
  const label=textNode('label','Archivo de destino'),select=document.createElement('select');select.id='attachClientTarget';
  const options=new Map([[batch,'Excel actual: '+currentExcelLabel(batch)],...historyFiles().map(f=>[f.batch,f.name]),['__new__','Crear un Excel nuevo']]);for(const [value,name] of options){const option=textNode('option',name);option.value=value;select.append(option);}label.append(select);
  const newLabel=textNode('label','Nombre del Excel nuevo'),name=document.createElement('input');name.id='attachNewName';name.maxLength=80;newLabel.append(name);newLabel.hidden=true;select.onchange=()=>newLabel.hidden=select.value!=='__new__';
  const status=textNode('p','');status.setAttribute('role','status');const actions=document.createElement('div');actions.className='workflow-actions';const cancel=textNode('button','Cancelar'),save=textNode('button','Agregar registro');cancel.className='secondary';save.className='primary';cancel.type=save.type='button';cancel.onclick=()=>attachDialog.close();actions.append(cancel,save);attachDialog.append(label,newLabel,status,actions);let busy=false;attachDialog.oncancel=e=>{if(busy)e.preventDefault();};
  save.onclick=async()=>{if(busy)return;let target=select.value;if(target==='__new__'&&!name.value.trim()){status.textContent='Escribe un nombre para el nuevo Excel.';name.focus();return;}busy=true;save.disabled=cancel.disabled=true;try{if(target==='__new__'){target='excel_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);const now=new Date().toISOString();await cloud.saveHistory({id:'hist_'+target,batch:target,name:name.value.trim(),created:now,updated:now,recordCount:0});const option=textNode('option',name.value.trim());option.value=target;select.append(option);select.value=target;newLabel.hidden=true;}
      const saved=await cloud.attachRecord(current._id,target,cloud.recordRevision(current));if(window.metlifeSelectedClient?._id===saved._id){window.metlifeSelectedClient=saved;if(editingRecord?._id===saved._id){editingRecord=saved;queueDraftSave();}renderSelectedClient();}attachDialog.close();await notifyClientUpdate(saved);
    }catch(error){status.textContent=error.message;}finally{busy=false;save.disabled=cancel.disabled=false;}};attachDialog.showModal();
}
const scopeLabel=textNode('label','Registros de '),scope=document.createElement('select');scope.id='recordScope';for(const [value,label] of [['current','Excel actual'],['cloud','Actividad reciente de toda la nube']]){const option=textNode('option',label);option.value=value;scope.append(option);}scope.value='cloud';scopeLabel.append(scope);document.querySelector('.records-toolbar').prepend(scopeLabel);scope.onchange=()=>{selectedRecords.clear();recordsPageSize=50;renderRecords();};
const retentionRenderRecords=renderRecords;
renderRecords=function(){retentionRenderRecords();const isCloud=scope.value==='cloud';get('recordsPageStatus').textContent='Mostrando '+Math.min(recordsPageSize,filteredRecords().length)+' de '+filteredRecords().length+(isCloud?' registros cargados de la nube':' en este Excel');if(isCloud)get('recordsMoreBtn').classList.toggle('hidden',!cloud.state.recentHasMore);for(const edit of get('recordsBody').querySelectorAll('.record-edit')){const item=records().find(r=>r._id===edit.dataset.id);if(!item)continue;const row=edit.closest('tr'),cell=edit.closest('td'),location=textNode('small',clientFileLabel(item));location.className='source-hint';cell.append(location);const action=textNode('button',!clientFile(item)&&item._batch!==batch?'Agregar a un Excel':'Quitar del Excel');action.type='button';action.className='link-btn '+(!clientFile(item)&&item._batch!==batch?'record-attach':'record-detach');action.dataset.id=item._id;cell.append(action);const remove=cell.querySelector('.record-trash');if(remove)remove.textContent='Eliminar cliente';}};
get('recordsMoreBtn').onclick=async()=>{recordsPageSize+=50;if(scope.value==='cloud'){get('recordsMoreBtn').disabled=true;try{await cloud.loadRecent(recordsPageSize);}catch(error){showToast('No se cargaron más registros',error.message,true);}finally{get('recordsMoreBtn').disabled=false;}}renderRecords();};
get('recordsBody').addEventListener('click',async e=>{const button=e.target.closest('.record-attach,.record-detach');if(!button||button.disabled)return;const item=records().find(r=>r._id===button.dataset.id);if(!item)return;button.disabled=true;try{if(button.classList.contains('record-attach'))await openAttachClient(item);else{if(!confirm('¿Quitar este registro del Excel? El cliente seguirá en la nube y podrás buscarlo por póliza o nombre.'))return;const saved=await cloud.detachRecord(item);await notifyClientUpdate(saved);}}catch(error){showToast('No se completó la acción',error.message,true);}finally{button.disabled=false;}});
const retentionRenderHistory=renderHistory;
renderHistory=function(){retentionRenderHistory();for(const row of get('historyList').querySelectorAll('.history-item')){const update=textNode('button','Actualizar Excel');update.type='button';update.className='history-action refresh';row.querySelector('.history-actions').append(update);}};
get('historyList').addEventListener('click',async e=>{const button=e.target.closest('.history-action.refresh');if(!button)return;const id=button.closest('.history-item').dataset.batch;button.disabled=true;try{await refreshArchive(id);if(archiveErrors.has(id))throw Error(archiveErrors.get(id));longClientNotice('El Excel «'+currentExcelLabel(id)+'» está actualizado con los registros que pertenecen a ese archivo. Puedes abrirlo desde el historial para revisar o copiar los datos, o descargar su versión actual.');}catch(error){showToast('No se actualizó el Excel',error.message,true);}finally{button.disabled=false;}});
const retentionContext=updateCaptureContext;
updateCaptureContext=function(){retentionContext();if(editingRecord&&editingRecord._batch!==batch&&!clientFile(editingRecord))get('currentExcelName').textContent='Estás actualizando: cliente en la nube (sin Excel guardado)';};
window.addEventListener('metlife:cloud-change',e=>{if(e.detail.type==='recent')renderRecords();if(e.detail.type==='history')renderSelectedClient();});
window.addEventListener('metlife:form-reset',renderSelectedClient);
renderSelectedClient();renderRecords();renderHistory();
