/* Work queues and review helpers. Photos stay in memory; saved data uses Firebase. */
(function(){
  'use strict';
  const el=id=>document.getElementById(id);let duplicateTimer,duplicateGeneration=0,duplicateSignature='',chooseResolve=null,chooseMatches=[],chooseItem=null;
  let pendingSnapshot=null,pendingVersion=0,pendingWriting=false,trashCursor=null,trashGeneration=0;
  const text=(tag,value)=>{const node=document.createElement(tag);node.textContent=value;return node;};
  function button(label,action){const b=text('button',label);b.type='button';b.className='secondary';b.onclick=async()=>{if(b.disabled)return;b.disabled=true;try{await action();}catch(error){showToast('No se completó la acción',error.message,true);}finally{b.disabled=false;}};return b;}
  function validate(){
    for(const key of ['telefono','correo','rfc','curp']){const input=el(key);if(!input)continue;let hint=el('validation-'+key);if(!hint){hint=text('small','');hint.id='validation-'+key;hint.className='validation-hint';hint.setAttribute('aria-live','polite');input.closest('.field').append(hint);input.setAttribute('aria-describedby',hint.id);}
      const value=input.value.trim();let message='';
      if(value){if(key==='telefono'&&!/^\d{10}$/.test(value))message='Revisa el teléfono: se esperan 10 dígitos.';
        if(key==='correo'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))message='Revisa el correo: parece faltar una parte de la dirección.';
        if(key==='rfc'&&!/^[A-ZÑ&]{3,4}\d{6}[A-Z0-9]{3}$/i.test(value))message='Revisa el RFC: su formato no coincide con los 12 o 13 caracteres esperados.';
        if(key==='curp'&&!/^[A-Z0-9]{18}$/i.test(value))message='Revisa la CURP: se esperan 18 letras y números.';}
      hint.textContent=message;hint.hidden=!message;input.classList.toggle('needs-review',!!message);
    }
  }
  function scheduleDuplicates(){
    if(!cloud.state.ready)return;const item=draft(),signature=JSON.stringify(['poliza','rfc','curp'].map(k=>item[k]));if(signature===duplicateSignature)return;duplicateSignature=signature;clearTimeout(duplicateTimer);const token=++duplicateGeneration;
    duplicateTimer=setTimeout(async()=>{try{const matches=await cloud.findDuplicates(item);if(token!==duplicateGeneration)return;const warning=el('duplicateWarning');warning.classList.toggle('show',!!matches.length);warning.textContent=matches.length?'Se encontraron '+matches.length+' registros con la misma póliza, RFC o CURP. Al guardar podrás compararlos y elegir actualizar o crear otra póliza.':'';}catch{if(token===duplicateGeneration){const warning=el('duplicateWarning');warning.textContent='No se pudo comprobar coincidencias en la nube. Se volverá a comprobar al guardar.';warning.classList.add('show');}}},450);
  }
  function comparison(){const selected=chooseMatches[Number(el('duplicateChoice').value)]?.record;el('duplicateComparison').replaceChildren();if(!selected)return;for(const field of fields.filter(f=>f.key!=='estatus')){const row=document.createElement('tr');row.append(text('th',field.label),text('td',selected[field.key]||'—'),text('td',chooseItem[field.key]||'—'));if(String(selected[field.key]||'')!==String(chooseItem[field.key]||''))row.className='changed-value';el('duplicateComparison').append(row);}}
  function chooseDuplicate(matches,item){chooseMatches=matches;chooseItem=item;el('duplicateChoice').replaceChildren();matches.forEach((hit,index)=>{const option=text('option',(hit.record.poliza||'Sin póliza')+' · '+(hit.record.nombre||'Sin nombre')+' · Coincide '+hit.key.toUpperCase());option.value=index;el('duplicateChoice').append(option);});comparison();el('duplicateDialog').showModal();return new Promise(resolve=>{chooseResolve=resolve;});}
  function finishChoice(action){const record=chooseMatches[Number(el('duplicateChoice').value)]?.record;el('duplicateDialog').close();const resolve=chooseResolve;chooseResolve=null;resolve?.(action?{action,record}:null);}
  el('duplicateChoice').onchange=comparison;el('duplicateCancel').onclick=()=>finishChoice();el('duplicateUpdate').onclick=()=>finishChoice('update');el('duplicateCreate').onclick=()=>finishChoice('create');el('duplicateDialog').addEventListener('cancel',event=>{event.preventDefault();finishChoice();});
  function renderPending(){el('pendingCount').textContent=cloud.state.pending.length;const list=el('pendingList');list.replaceChildren();const items=cloud.state.pending.slice().sort((a,b)=>String(b.updated).localeCompare(String(a.updated)));if(!items.length)list.append(text('p','No tienes capturas pendientes.'));items.forEach(entry=>{const row=document.createElement('article');row.append(text('strong',entry.name||entry.draft?.nombre||'Captura pendiente'),text('p',entry.reason||'Pendiente de completar'));const actions=document.createElement('div');actions.className='workflow-actions';actions.append(button('Continuar',async()=>{if(pendingWorkspace)throw Error('Resuelve primero el conflicto del borrador.');if(fields.some(f=>el(f.key).value)&&!confirm('¿Reemplazar el formulario por esta captura pendiente?'))return;applySharedWorkspace({...cloud.state.workspace,batch:entry.batch,draft:entry.draft,metadata:entry.metadata||{},editingRecord:null,pendingId:entry.id,pendingRevision:entry.revision});queueDraftSave();validate();el('clientForm').scrollIntoView({behavior:'smooth'});}),button('Eliminar pendiente',async()=>{if(!confirm('¿Eliminar esta captura pendiente?'))return;await cloud.removePending(entry.id,entry.revision);if(activePendingId===entry.id){activePendingId=null;activePendingRevision=null;queueDraftSave();}}));row.append(actions);list.append(row);});}
  el('savePendingBtn').onclick=()=>{if(pendingWorkspace)return showToast('Revisa el borrador','Resuelve primero el conflicto con la nube.',true);if(!Object.values(draft()).some(Boolean))return showToast('Formulario vacío','Escribe o escanea algún dato antes de guardarlo como pendiente.');pendingSnapshot={draft:draft(),metadata:captureMetadata(),batch,...(activePendingId?{id:activePendingId}:{}),expected:activePendingRevision};pendingVersion=draftVersion;const old=cloud.state.pending.find(p=>p.id===activePendingId);el('pendingName').value=old?.name||pendingSnapshot.draft.nombre||pendingSnapshot.draft.poliza||'CAPTURA PENDIENTE';el('pendingReason').value=old?.reason||'';el('pendingStatus').textContent='';el('pendingDialog').showModal();};
  el('pendingCancel').onclick=()=>{if(!pendingWriting)el('pendingDialog').close();};el('pendingDialog').addEventListener('cancel',event=>{if(pendingWriting)event.preventDefault();});
  el('pendingConfirm').onclick=async()=>{if(pendingWriting||!pendingSnapshot)return;const name=el('pendingName').value.trim();if(!name){el('pendingStatus').textContent='Escribe un nombre para identificar la captura.';return;}pendingWriting=true;el('pendingConfirm').disabled=true;
    try{const {expected,...entry}=pendingSnapshot;await cloud.savePending({...entry,name,reason:el('pendingReason').value.trim()},entry.id?expected:undefined);el('pendingDialog').close();if(draftVersion===pendingVersion)clearForm();showToast('Pendiente guardado en la nube','Puedes continuar con otra póliza y recuperarlo desde tu cuenta.');}catch(error){el('pendingStatus').textContent=error.message;}finally{pendingWriting=false;el('pendingConfirm').disabled=false;}
  };
  function renderSellers(){el('vendida').setAttribute('list','sellerNames');el('sellerNames').replaceChildren();el('sellersList').replaceChildren();cloud.state.sellers.slice().sort((a,b)=>a.name.localeCompare(b.name,'es')).forEach(seller=>{const option=document.createElement('option');option.value=seller.name;el('sellerNames').append(option);const row=document.createElement('article');row.append(text('strong',seller.name),button('Quitar de frecuentes',()=>cloud.removeSeller(seller.id)));el('sellersList').append(row);});}
  el('rememberSellerBtn').onclick=async()=>{const b=el('rememberSellerBtn');b.disabled=true;try{await cloud.saveSeller(el('vendida').value);showToast('Nombre frecuente guardado','Disponible en VENDIDA desde los otros dispositivos.');}catch(error){showToast('No se guardó el nombre',error.message,true);}finally{b.disabled=false;}};
  async function loadTrash(more=false){const token=++trashGeneration;el('refreshTrashBtn').disabled=true;el('trashMoreBtn').disabled=true;el('trashStatus').textContent='Cargando papelera…';try{const page=await cloud.listTrash(more?trashCursor:null);if(token!==trashGeneration)return;if(!more)el('trashList').replaceChildren();trashCursor=page.cursor;for(const item of page.items){const row=document.createElement('article');row.append(text('strong',(item.poliza||'Sin póliza')+' · '+(item.nombre||'Sin nombre')),text('p','Recuperable hasta '+new Date(item._expiresAt).toLocaleDateString('es-MX')),button('Restaurar',async()=>{await cloud.restoreRecord(item._id);await loadTrash();showToast('Registro restaurado','Está de nuevo en su archivo original y en la búsqueda de clientes.');}));el('trashList').append(row);}el('trashStatus').textContent=el('trashList').children.length?'':'La papelera está vacía.';el('trashMoreBtn').classList.toggle('hidden',!trashCursor);}catch(error){el('trashStatus').textContent=error.message;}finally{if(token===trashGeneration){el('refreshTrashBtn').disabled=false;el('trashMoreBtn').disabled=false;}}}
  el('trashPanel').addEventListener('toggle',()=>{if(el('trashPanel').open)loadTrash();});el('refreshTrashBtn').onclick=()=>loadTrash();el('trashMoreBtn').onclick=()=>loadTrash(true);
  el('recordsBody').addEventListener('click',async event=>{const b=event.target.closest('.record-trash,.record-uncopy');if(!b||b.disabled)return;const item=records().find(r=>r._id===b.dataset.id);if(!item)return;b.disabled=true;try{if(b.classList.contains('record-trash')){if(!confirm('¿Mover esta póliza a la papelera? Podrás restaurarla durante 3 meses.'))return;await cloud.trashRecord(item);showToast('Registro en la papelera','Puedes recuperarlo durante 3 meses.');if(el('trashPanel').open)loadTrash();}else await cloud.markCopied([item],true);}catch(error){showToast('No se completó la acción',error.message,true);}finally{b.disabled=false;}});
  el('copiedFilter').onchange=()=>{selectedRecords.clear();recordsPageSize=50;renderRecords();};el('recordsMoreBtn').onclick=()=>{recordsPageSize+=50;renderRecords();};
  window.addEventListener('metlife:cloud-change',event=>{if(['pending','ready'].includes(event.detail.type))renderPending();if(['sellers','ready'].includes(event.detail.type))renderSellers();if(event.detail.type==='records'){duplicateSignature='';scheduleDuplicates();}if(event.detail.type==='migration')el('cloudStatus').textContent='Preparando búsqueda: '+event.detail.value+' registros';});
  window.addEventListener('metlife:form-reset',()=>{clearTimeout(duplicateTimer);duplicateGeneration++;duplicateSignature='';queueMicrotask(validate);});el('clientForm').addEventListener('input',validate);
  window.metlifeWorkflow={validate,scheduleDuplicates,chooseDuplicate};renderPending();renderSellers();validate();
})();
